version: '3'
services:
  backend-app:
    container_name: backend-app
    restart: always
    ports:
      - '8072:8000'
    build:
      context: .
      dockerfile: ./apps/evs-server/.Dockerfile
    networks:
      - app-network

  frontend-app:
    container_name: frontend-app
    restart: always
    ports:
      - '8090:80'
    depends_on:
      - backend-app
    build:
      context: .
      dockerfile: ./apps/evs-test/.Dockerfile

networks:
  app-network:
